config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:  "homes#top"
  get "/home/about" =>"homes#about"
   resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
   end 
   resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 belongs_to :user
 has_many :book_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_one_attached :profile_image

 validates :title, presence: true
 validates :body, presence: true, length: { maximum: 200 }
 
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
   belongs_to :user
   belongs_to :book
    
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image

 def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
 end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
      root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
    redirect_to request.referer
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to request.referer
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end









end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
     book = Book.find(params[:id])
    if book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 def top
  
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
 end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/book_comments/_book_comment.html.erb
<%= form_with model: [book, book_comment] do |f| %>
  <%= f.text_area :comment, placeholder: "コメントをここに", class: "w-100" %>
  <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <tbody>
      <% book.book_comments.each do |book_comment| %>
      <tr>
        
        <td>
          <%= link_to user_path(book_comment.user) do %>
            <%= image_tag book_comment.user.get_profile_image(100,100) %><br>
            <%= book_comment.user.name %>
          <% end %>
        </td>
        <td><%= book_comment.comment %></td>
        <td>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/books/_book.html.erb
<%= form_with model:book do |f| %>
  <div class="form-title row">
    <%= f.label :Title %>
    <%= f.text_field :title, class: "col-xs-12"%>
  </div>

  <div class="form-body row">
  	<%= f.label :Opinion %>
    <%= f.text_area :body, class: "col-xs-12"%>
  </div>



  <div class="actions row">
    <%= f.submit class: "btn btn-primary col-xs-12"%>
  </div>
<% end %>

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <h1>Editing Book</h1>
      <%= render 'books/error', model: @book %>
      <%= render 'books/book', book: @book %>
    <div class="menu">
      <%= link_to "Show", book_path(@book) %>
      
      <%= link_to "Back", books_path %>
    </div>
    </div>
  <div class="col-xs-3"></div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'books/error', model: @book %>
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
     <div class="col-md-8 offset-md-1">
      <table class="table book-index">
        <h2>Books</h2>
        <thead>
          <th>Title</th>
          <th>Opinion</th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do%>
                <%= image_tag book.user.get_profile_image(80,80) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            <td><%= render "favorites/btn", book: book %></td>
            <td>コメント数: <%= @book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table table-user-show">
        <tr>

          <td>
                <%= link_to user_path(@book.user.id) do%>
                <%= image_tag @book.user.get_profile_image(80,80) %>
                <% end %>
          <%= link_to @user.name, user_path(@user) %>
          </td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <td>コメント数: <%= @book.book_comments.count %></td>
           <td><%= render "favorites/btn", book: @book %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
          <% end %>
        </tr>
      </table>
      <%= render "book_comments/index", book: @book %>
      <%= render "book_comments/book_comment", book: @book, book_comment: @book_comment %>

    </div>
  </div>
</div>

app/views/favorites/_btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% end %>

app/views/homes/about.html.erb
<h1>Welcom to
  <i class="fas fa-book"></i><b>Bookers!!</b>
</h1>

app/views/homes/top.html.erb
<div class="container">
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<i class="fas fa-book"></i>
		
			<strong>Bookers</strong>  !!</h1>
			<p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
    <style type="text/css">
      .turbolinks-progress-bar {
       position: fixed;
       display: block;
       top: 0;
       left: 0;
       height: 3px;
       background:#0076ff;
       z-index:9999;
       transition:width 300ms ease-out, opcity 150ms 150ms ease-in;
       transform: translated3d(0, 0, 0);
    }
    </style>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <title>Bookers2</title>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">
            <span>Bookers</span>
        </a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
          <div class="navbar-collapse collapse show" id=navbarNavDropdown style>
          <ul class="nav navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user), class:"nav-link text-light" do %>
                <i class="fas fa-home"></i>Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path, class:"nav-link text-light" do %>
                <i class="fas fa-users"></i>Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path, class:"nav-link text-light" do %>
                <i class="fas fa-book-open"> </i>Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                <i class="fas fa-sign-out-alt"> </i>Log out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path,class:"nav-link text-light" do %>
                <i class="fas fa-home"></i>Home
                <% end %> 
              </li>
              <li>
                <%= link_to home_about_path, class:"nav-link text-light" do %>
                <i class="fas fa-link"></i>About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                <i class="fas fa-user-plus"></i>Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                <i class="fas fa-sign-in-alt"></i>Log in
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
     </nav>
    </header>  
    <main>
      <p id="notice"><%= flash[:notice] %></p>
      <%= yield %>
  </main> 
  <footer>
   <div class="container mt-5">
    <div class="row">
     <div class="mx-auto">
        <p> CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
</body>
</html>

app/views/users/_user.html.erb
<table class="table table-user">
  <h2>User info</h2>
  <thead>
    <tr>
    <%=image_tag user.get_profile_image(100,100)%>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>Introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th colspan="2">
        <%= link_to edit_user_path(user), class:"btn btn-outline-secoundary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
      </th>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_with model:@user do |f| %>
<%= render 'books/error', model: @user %>
  <label for="inputName">Name</label>
    <%= f.text_field :name,autofocus: true, id:"inputName", placeholder:"名前" %>
  <label for="inputImage">Image</label>
    <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <lavel for="inputintroduction">Introduction</label>
    <%= f.text_area :introduction %><br>
  <div class="upload">
    <%= f.submit " Update User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
     <div class="col-md-8 offset-md-1">
  	  <table class="table table-sm user-index">
	  	  <h2>Users</h2>
        <thead>
          <th>image</th>
          <th>name</th>
          <th></th>
  	    </thead>
  	  	<tbody>
  	  	  <% @users.each do |user| %>
	  	  	<tr>
	  	  	  <td>
            <%=image_tag user.get_profile_image(50,50)%>
	  	  	  </td>
	  	  	  <td><%= user.name %></td>
	  	  	  <td><%= link_to "Show", "/users/#{user.id}" %></td>
	  	  	</tr>
  	  	  <% end %>
  	  	</tbody>
  	  </table>
  	</div>
  </div>
  <div></div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table table-user-show">
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(@user) do %>
            <% end %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
               <td><%= render "favorites/btn", book: book %></td>
            <td>コメント数: <%= book.book_comments.count %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>